---
- hosts: ios
  gather_facts: no

  tasks:
    - name: create directory  # (a)
      file:
        state: directory
        path: "logs/{{ now(False, '%Y%m%d_%H%M_%S') }}"
      register: d
      run_once: yes

    - name: gather facts  # (b)
      ios_facts:

    - name: execute show commands  # (c)
      ios_command:
        commands: "{{ commands }}"
      register: result

    - name: output to files  # (d)
      copy:
        content: "{{ result.stdout[ansible_loop.index0] }} "
        dest: "{{ d.path }}/{{ inventory_hostname }}_{{ item | replace(' ', '_') }}.log"
      loop: "{{ commands }}"
      loop_control:
        extended: yes
        
    - name: create report  # (e)
      template:
        src: report.md.j2
        dest: "{{ d.path }}/report.md"
      run_once: yes
